import { Injectable } from '@angular/core';

@Injectable()
export class DataService {

  constructor() { }

  getAll() { 
    var data = [
      {
        "Group": "CCA",
        "Application": "CCA - ATNA audit log server",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 4,
        "vCPU": 1,
        "RAID5GP1": 60,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "See installation  manual DOC1474072"
      },
      {
        "Group": "CCA",
        "Application": "CCA - ATNA audit log DB server",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 4,
        "vCPU": 1,
        "RAID5GP1": 125,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "OS - 60GB / DB - 65GB expanding based upon data retention policy requirements / See installation  manual DOC1474072"
      },
      {
        "Group": "CCA",
        "Application": "CCA - ATR/MM/UV-ZFP-XDS database server",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 12,
        "vCPU": 4,
        "RAID5GP1": 350,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 200,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS/Database selected off of calculation tab / If ILM, Migrations, XDS submissions, etc., then memory needs to be increased to meet appropriate needs of all activities."
      },
      {
        "Group": "CCA",
        "Application": "CCA - AIM Standalone Server",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 6,
        "vCPU": 6,
        "RAID5GP1": 60,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS"
      },
      {
        "Group": "CCA",
        "Application": "CCA - EA Database only",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 4,
        "vCPU": 4,
        "RAID5GP1": 60,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 500,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS / Database selected off of calculation tab"
      },
      {
        "Group": "CCA",
        "Application": "CCA - EA all-in-one (Standalone)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 10,
        "vCPU": 12,
        "RAID5GP1": 60,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 300,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS / Database selected off of calculation tab / If ILM, Migrations, XDS submissions, etc., then memory needs to be increased to meet appropriate needs of all activities."
      },
      {
        "Group": "CCA",
        "Application": "CCA - EA App Server primary",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 6,
        "vCPU": 8,
        "RAID5GP1": 60,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60GB OS / If ILM, Migrations, XDS submissions, etc., then memory needs to be increased to meet appropriate needs of all activities."
      },
      {
        "Group": "CCA",
        "Application": "CCA - EA App Server secondary",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 6,
        "vCPU": 4,
        "RAID5GP1": 60,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60GB OS"
      },
      {
        "Group": "CCA",
        "Application": "CCA - UV-ZFP combined application and database (DICOM & XDS database for PIV) (50 CCU)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 32,
        "vCPU": 8,
        "RAID5GP1": 92,
        "RAID10GP2": 0,
        "RAID5GP3": 300,
        "RAID5GP4": 0,
        "IOPS": 500,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS/150>GB - Cache - can be on another drive and adjusted for the site /  Database is calcultate based on records entered on the calculation tap P10, each record is 10K, and addition 2GB is added to cover filters, flags, and user audits, recommended database be slit out into it's own RAID group."
      },
      {
        "Group": "CCA",
        "Application": "CCA - UV-ZFP database (XDS Database for PIV)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 16,
        "vCPU": 4,
        "RAID5GP1": 92,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 200,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS/ Database is calcultate based on records entered on the calculation tap P10, each record is 10K, and addition 2GB is added to cover filters, flags, and user audits"
      },
      {
        "Group": "CCA",
        "Application": "CCA - UV-ZFP Application node only  (DICOM &/or XDS apps server) (50 CCU)",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 16,
        "vCPU": 4,
        "RAID5GP1": 60,
        "RAID10GP2": 0,
        "RAID5GP3": 300,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS/150GB Cache - can be on another drive and adjusted for the site"
      },
      {
        "Group": "CCA",
        "Application": "CCA - GE (ICW) XDS Registry DB server",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 116,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 210,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "500GB (10K RPM) RAID 1 - (5) disk drives  (>70GB 15K RPM RAID 1 (OS) & 1TB iSCSI or fiber channel SAN or Solid State drives RAID recommended), Each Patient Registration uses 10kb, Each Document Registration uses 12kb, NOTE:  Example of 1 Million Patients and 500,000 documents uses at least 16GB of database disk space."
      },
      {
        "Group": "CCA",
        "Application": "CCA - GE (ICW) XDS Registry App server",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 80,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 500,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "600GB disk space minimum  (>70GB 15K RPM RAID 10 recommended)"
      },
      {
        "Group": "CCA",
        "Application": "CCA - Media Manager app for load balance",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 60,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS"
      },
      {
        "Group": "CCA",
        "Application": "CCA - Media Manager with Database only",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 160,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS/100GB database"
      },
      {
        "Group": "CCA",
        "Application": "CCA - Media Manager with app and Database",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 8,
        "vCPU": 4,
        "RAID5GP1": 160,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS/100GB database"
      },
      {
        "Group": "CCA",
        "Application": "CCA - ICW eMPI Database server",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 77,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 500,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60GB - OS / _ Each Patient Local MRN Record uses 3.5kb + 3.5kb for enterprise account"
      },
      {
        "Group": "CCA",
        "Application": "CCA - ICW eMPI web server",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 8,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 240,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60GB - OS / Additional 20kb per message"
      },
      {
        "Group": "CCA",
        "Application": "CCA - NextGate eMPI DB server (3.75GB database per 1 Million records)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 80,
        "vCPU": 20,
        "RAID5GP1": 0,
        "RAID10GP2": 79,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 500,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS/ database data base is calculated with 3.75K per record entered on the calculation tab K8 / CPU is calculated from J8"
      },
      {
        "Group": "CCA",
        "Application": "CCA - NextGate eMPI App server (Supports 200K transactions per day)",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 16,
        "vCPU": 4,
        "RAID5GP1": 0,
        "RAID10GP2": 60,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS/"
      },
      {
        "Group": "CCA",
        "Application": "CCA - CCG Server with no Database or DMWL.",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 12,
        "vCPU": 4,
        "RAID5GP1": 0,
        "RAID10GP2": 100,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "XDS Registry: 50 GB / eMPI: 10 GB / rounded up to 100 GB including Windows OS"
      },
      {
        "Group": "CCG",
        "Application": "CCG - Large/regional, msg only, no DMWL",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 12,
        "vCPU": 4,
        "RAID5GP1": 265,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "For a CCG in a datacenter of a regional project, or at a very large site, without DICOM Modality Work List."
      },
      {
        "Group": "CCG",
        "Application": "CCG - Small/local, messaging only, no DMWL",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 12,
        "vCPU": 4,
        "RAID5GP1": 265,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "For a local CCG at a small to mid-size site, without DICOM Modality Work List."
      },
      {
        "Group": "CCG",
        "Application": "CCG - with database (DMWL)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 12,
        "vCPU": 4,
        "RAID5GP1": 265,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 300,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "CCG with a DICOM Modality Work List (requires a SQL server license)"
      },
      {
        "Group": "CCW",
        "Application": "CCW - App Server",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 8,
        "vCPU": 8,
        "RAID5GP1": 100,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "More than 80 CCU ( plus Database server)"
      },
      {
        "Group": "CCW",
        "Application": "CCW - Database Server Large",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 24,
        "vCPU": 12,
        "RAID5GP1": 1229,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 600,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "More  than 80 CCU and more than 20000 studies /year ( plus Application Server)"
      },
      {
        "Group": "CCW",
        "Application": "CCW - Database Server Medium",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 24,
        "vCPU": 8,
        "RAID5GP1": 900,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 500,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "More than 80 CCU and less than 20000 studies /year ( plus Application Server)"
      },
      {
        "Group": "CCW",
        "Application": "CCW - Database/App Server (Large)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 24,
        "vCPU": 12,
        "RAID5GP1": 1229,
        "RAID10GP2": 300,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 600,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Up to 80 CCU and more than 20000 studies /year"
      },
      {
        "Group": "CCW",
        "Application": "CCW - Database/App Server (Medium)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 24,
        "vCPU": 8,
        "RAID5GP1": 900,
        "RAID10GP2": 300,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 500,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Up to 80 CCU and less than 20000 studies /year"
      },
      {
        "Group": "CCW",
        "Application": "CCW - Interface server",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 8,
        "vCPU": 12,
        "RAID5GP1": 100,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "1 per site"
      },
      {
        "Group": "CCW",
        "Application": "CCW - TEST Database/App Server",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 600,
        "RAID10GP2": 300,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - CDPS",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 2,
        "vCPU": 2,
        "RAID5GP1": 76,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - DAS",
        "OS": "RHEL5.8/6.8",
        "Database": "",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 76,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - DBRep",
        "OS": "RHEL5.8/6.8",
        "Database": "",
        "vRAM": 8,
        "vCPU": 4,
        "RAID5GP1": 76,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - IMS 1800-3500TB",
        "OS": "RHEL5.8/6.8",
        "Database": "Sybase 12.5.4/15.7",
        "vRAM": 64,
        "vCPU": 16,
        "RAID5GP1": 7772,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 2000,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "76 GB - OS/216 GB - Logs/3708 GB - IMS/3772 GB - DBCC"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - IMS 550-1800GB",
        "OS": "RHEL5.8/6.8",
        "Database": "Sybase 12.5.4/15.7",
        "vRAM": 64,
        "vCPU": 16,
        "RAID5GP1": 4172,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 1500,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "76 GB - OS/216 GB - Logs/1908 GB - IMS/1972 GB - DBCC"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - IMS 300-550GB",
        "OS": "RHEL5.8/6.8",
        "Database": "Sybase 12.5.4/15.7",
        "vRAM": 32,
        "vCPU": 16,
        "RAID5GP1": 1528,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 1000,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "76 GB - OS/216 GB - Logs/584 GB - IMS/652 GB - DBCC"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - IMS 300GB",
        "OS": "RHEL5.8/6.8",
        "Database": "Sybase 12.5.4/15.7",
        "vRAM": 16,
        "vCPU": 4,
        "RAID5GP1": 1000,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 300,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "76 GB - OS/216 GB - Logs/324 GB - IMS/384 GB - DBCC"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - Coord",
        "OS": "RHEL5.8/6.8",
        "Database": "",
        "vRAM": 8,
        "vCPU": 4,
        "RAID5GP1": 76,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "GigE",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - ITS/C2C",
        "OS": "RHEL5.8/6.8",
        "Database": "",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 76,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - IV Image Volume (one per 12TB of NAS to expose from SAN)",
        "OS": "RHEL5.8/6.8",
        "Database": "",
        "vRAM": 4,
        "vCPU": 4,
        "RAID5GP1": 176,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - SPS Monitoring server",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 85,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - UV - AW Server node (16k / 8k slices for small node)",
        "OS": "Suse Linux 11",
        "Database": "",
        "vRAM": 24,
        "vCPU": 8,
        "RAID5GP1": "",
        "RAID10GP2": 70,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 300,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "70GB - OS - 4 users per node, 6 nodes max"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - UV Controller w/ UV database",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 300,
        "RAID10GP2": 60,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 300,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60GB - OS, 300GB - Data partition"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - UV Node (up to 50 CCU per node)",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 300,
        "RAID10GP2": 60,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60GB - OS, 300GB - Data partition"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - UV Node (up to 50 CCU per node) - Separate UV web server OR Dakota",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 32,
        "vCPU": 8,
        "RAID5GP1": 250,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "250GB - OS, Data partition"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - UV-ZFP server (600 st/hr, max 50 CCU)",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 32,
        "vCPU": 8,
        "RAID5GP1": 60,
        "RAID10GP2": 300,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 210,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60GB - OS, 300GB - Data partition - 8GB is the minimum spec"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - XED Services (Xbus and/or X-Services ; or up to 4 X-Provider)",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 8,
        "vCPU": 8,
        "RAID5GP1": 60,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60GB - OS+Application"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - Workflow Manager (WFM)",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 250,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "These are the basic settings, consult customers environmant for true settings. Consult SES"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - WFM Admin Desktop",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 8,
        "vCPU": 4,
        "RAID5GP1": 50,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "50 GB - OS + Application - Can use existing ZFP Admin Desktop server"
      },
      {
        "Group": "CPACS",
        "Application": "CPACS - XE Services standalone mode (WFM)",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 60,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "60 GB - OS + Application - Supports all components and datasources (CPACS)"
      },
      {
        "Group": "CRMA",
        "Application": "CRMA (2D only)",
        "OS": "RHEL6.4",
        "Database": "",
        "vRAM": 8,
        "vCPU": 1,
        "RAID5GP1": 20,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "When calculating CRMA QTY is CC users and add the amount of images in a study that will be viewed, 200 is a good average if unknown"
      },
      {
        "Group": "DoseWatch",
        "Application": "DoseWatch - App server",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 8,
        "vCPU": 4,
        "RAID5GP1": 50,
        "RAID10GP2": 0,
        "RAID5GP3": 50,
        "RAID5GP4": 0,
        "IOPS": 75,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "DoseWatch",
        "Application": "DoseWatch - DB Analytics",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 10,
        "vCPU": 4,
        "RAID5GP1": 50,
        "RAID10GP2": 0,
        "RAID5GP3": 1000,
        "RAID5GP4": 0,
        "IOPS": 150,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Not yet available but added for future usage."
      },
      {
        "Group": "DoseWatch",
        "Application": "DoseWatch - DB Server",
        "OS": "MS 2012 R2 Std",
        "Database": "MySQL 5.5.36",
        "vRAM": 10,
        "vCPU": 4,
        "RAID5GP1": 50,
        "RAID10GP2": 0,
        "RAID5GP3": 250,
        "RAID5GP4": 0,
        "IOPS": 150,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "250 GB is the thin provisioning but it could growth up to 2Tb"
      },
      {
        "Group": "DoseWatch",
        "Application": "DoseWatch - Serphylink",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 6,
        "vCPU": 2,
        "RAID5GP1": 50,
        "RAID10GP2": 0,
        "RAID5GP3": 50,
        "RAID5GP4": 0,
        "IOPS": 75,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "LB",
        "Application": "LB - A10 vThunder 1 Gbps Load Balancer",
        "OS": "Linux/ACOS",
        "Database": "",
        "vRAM": 4,
        "vCPU": 1,
        "RAID5GP1": 15,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "15 GB - OS + Application - Use vThunder_271_GR1_P3.ova"
      },
      {
        "Group": "LB",
        "Application": "LB - A10 vThunder 4 Gbps Load Balancer",
        "OS": "Linux/ACOS",
        "Database": "",
        "vRAM": 12,
        "vCPU": 2,
        "RAID5GP1": 15,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "15 GB - OS + Application - Use vThunder_271_GR1_P3.ova"
      },
      {
        "Group": "LB",
        "Application": "LB - F5 Virtual Edition 1 Gbps Load Balancer",
        "OS": "CentOS6.6/TMOS",
        "Database": "",
        "vRAM": 8,
        "vCPU": 4,
        "RAID5GP1": 20,
        "RAID10GP2": 142,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "162 GB - OS + Application - Use BIGIP-12.1.2.0.0.249.ALL-scsi.ova"
      },
      {
        "Group": "LB",
        "Application": "LB - F5 Virtual Edition 3 Gbps Load Balancer",
        "OS": "CentOS6.6/TMOS",
        "Database": "",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 20,
        "RAID10GP2": 142,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "162 GB - OS + Application - Use BIGIP-12.1.2.0.0.249.ALL-scsi.ova"
      },
      {
        "Group": "Misc.",
        "Application": "Misc. - vCenter",
        "OS": "Appliance (Linux)",
        "Database": "",
        "vRAM": 8,
        "vCPU": 2,
        "RAID5GP1": 125,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 10,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "See: http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1003882"
      },
      {
        "Group": "Misc.",
        "Application": "Misc. - Windows domain/AD server",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 50,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 10,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "Misc.",
        "Application": "Misc. - Windows VM large",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 16,
        "vCPU": 4,
        "RAID5GP1": 200,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 10,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Generic VM"
      },
      {
        "Group": "Misc.",
        "Application": "Misc. - Windows VM medium",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 8,
        "vCPU": 2,
        "RAID5GP1": 150,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 10,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Generic VM"
      },
      {
        "Group": "Misc.",
        "Application": "Misc. - Windows VM small",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 100,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 10,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Generic VM"
      },
      {
        "Group": "OnWatch",
        "Application": "OnWatch - Large (<8000 checks)",
        "OS": "Ubuntu",
        "Database": "",
        "vRAM": 6,
        "vCPU": 6,
        "RAID5GP1": 120,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "The disk size is highly dependent on the design of the checks and the use of graphs, each check creates its own database file."
      },
      {
        "Group": "OnWatch",
        "Application": "OnWatch - Medium (<3000 checks)",
        "OS": "Ubuntu",
        "Database": "",
        "vRAM": 4,
        "vCPU": 4,
        "RAID5GP1": 80,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 75,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "The disk size is highly dependent on the design of the checks and the use of graphs, each check creates its own database file."
      },
      {
        "Group": "OnWatch",
        "Application": "OnWatch - Small (<1500 checks)",
        "OS": "Ubuntu",
        "Database": "",
        "vRAM": 2,
        "vCPU": 2,
        "RAID5GP1": 40,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "The disk size is highly dependent on the design of the checks and the use of graphs, each check creates its own database file."
      },
      {
        "Group": "OnWatch",
        "Application": "OnWatch - X-Large (>8000 checks)",
        "OS": "Ubuntu",
        "Database": "",
        "vRAM": 8,
        "vCPU": 8,
        "RAID5GP1": 120,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 200,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "The disk size is highly dependent on the design of the checks and the use of graphs, each check creates its own database file."
      },
      {
        "Group": "PACS",
        "Application": "PACS IW - UV - AW Server node (16k slices)",
        "OS": "Suse Linux 11",
        "Database": "",
        "vRAM": 24,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 70,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 300,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "70GB - OS - 4 users per node, 6 nodes max"
      },
      {
        "Group": "PACS",
        "Application": "PACS IW - UV Controller and database",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 8,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 370,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 300,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "PACS",
        "Application": "PACS IW - UV Controller or node  (up to 50 CCU per node)",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 8,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 170,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "PACS",
        "Application": "PACS IW - UV Database",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 8,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 370,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 300,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "RIS-I",
        "Application": "RIS-I - Add-on server - Print, Fax, VR, Interface",
        "OS": "MS 2008 R2 Std",
        "Database": "",
        "vRAM": 16,
        "vCPU": 6,
        "RAID5GP1": 279,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Grp 1 is OS and apps (C:/128gb, E:/96Gb, T:/55Gb)"
      },
      {
        "Group": "RIS-I",
        "Application": "RIS-I - Citrix Server (18 non VR clients or 12 VR clients)",
        "OS": "MS 2008 R2 Std",
        "Database": "",
        "vRAM": 32,
        "vCPU": 6,
        "RAID5GP1": 150,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Grp 1 is OS and apps (C:, E:, T:)"
      },
      {
        "Group": "RIS-I",
        "Application": "RIS-I - DB server large (400 CCU)",
        "OS": "MS 2008 R2 Ent",
        "Database": "Oracle 10gR2",
        "vRAM": 128,
        "vCPU": 16,
        "RAID5GP1": 192,
        "RAID10GP2": 748,
        "RAID5GP3": 176,
        "RAID5GP4": 0,
        "IOPS": 500,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Grp 1 is OS and apps (C: / 192Gb), Grp 2 is Oracle (E:/558Gb, R:/103Gb ; T: / 87Gb), Grp 3 is network shares (H:/160Gb, I:/16Gb, Q:/100Mb in cluster mode only) - no thin provisioning!"
      },
      {
        "Group": "RIS-I",
        "Application": "RIS-I - DB server medium (200 CCU)",
        "OS": "MS 2008 R2 Ent",
        "Database": "Oracle 10gR2",
        "vRAM": 64,
        "vCPU": 8,
        "RAID5GP1": 192,
        "RAID10GP2": 469,
        "RAID5GP3": 176,
        "RAID5GP4": 0,
        "IOPS": 400,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Grp 1 is OS and apps (C: / 192Gb), Grp 2 is Oracle (E:/279Gb, R:/103Gb ; T: / 87Gb), Grp 3 is network shares (H:/160Gb, I:/16Gb, Q:/100Mb in cluster mode only) - no thin provisioning!"
      },
      {
        "Group": "RIS-I",
        "Application": "RIS-I - DB server small (100 CCU)",
        "OS": "MS 2008 R2 Std",
        "Database": "Oracle 10gR2",
        "vRAM": 32,
        "vCPU": 6,
        "RAID5GP1": 192,
        "RAID10GP2": 280,
        "RAID5GP3": 56,
        "RAID5GP4": 0,
        "IOPS": 300,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Grp 1 is OS and apps (C: / 192Gb), Grp 2 is Oracle (E:/192Gb, R:/31Gb ; T: / 87Gb), Grp 3 is network shares (H:/48Gb, I:/8Gb, Q:/100Mb in cluster mode only) - no thin provisioning!"
      },
      {
        "Group": "RIS-I",
        "Application": "RIS-I - Test DB server",
        "OS": "MS 2008 R2 Std",
        "Database": "Oracle 10gR2",
        "vRAM": 16,
        "vCPU": 2,
        "RAID5GP1": 250,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Grp 1 is for all partitions on a test server. Additional disk space might be needed if tests use a copy of the real production database."
      },
      {
        "Group": "RIS-I",
        "Application": "RIS-I - Test Web or Citrix server",
        "OS": "MS 2008 R2 Std",
        "Database": "",
        "vRAM": 16,
        "vCPU": 2,
        "RAID5GP1": 150,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Grp 1 is for all partitions."
      },
      {
        "Group": "RIS-I",
        "Application": "RIS-I - Web server large for eRadCockpit and WebMFD - single or LB srvr (80 CCU)",
        "OS": "MS 2008 R2 Ent",
        "Database": "",
        "vRAM": 128,
        "vCPU": 8,
        "RAID5GP1": 192,
        "RAID10GP2": 87,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Grp 1 is OS and apps (C:/192Gb), Grp 2 (T:/92Gb) / Each Virtual Server will be handled as Software-Only"
      },
      {
        "Group": "RIS-I",
        "Application": "RIS-I - Web server medium for eRadCockpit and WebMFD - single or load-bal. srvr (30 CCU)",
        "OS": "MS 2008 R2 Ent",
        "Database": "",
        "vRAM": 64,
        "vCPU": 8,
        "RAID5GP1": 192,
        "RAID10GP2": 87,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Grp 1 is OS and apps (C:/192Gb), Grp 2 (T:/92Gb) / Each Virtual Server will be handled as Software-Only"
      },
      {
        "Group": "RIS-I",
        "Application": "RIS-I - Web server small for WebMFD only",
        "OS": "MS 2008 R2 Std",
        "Database": "",
        "vRAM": 12,
        "vCPU": 2,
        "RAID5GP1": 100,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "C360",
        "Application": "C360 - HAProxy Server",
        "OS": "CentOS6.5 - 64bits",
        "Database": "",
        "vRAM": 2,
        "vCPU": 2,
        "RAID5GP1": 20,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 10,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "> 10 GB for OS > 10 GB for apps -  Deploy in PUBLIC VLAN"
      },
      {
        "Group": "C360",
        "Application": "C360 - Web App Server (Play&DocViewer)",
        "OS": "CentOS6.5 - 64bits",
        "Database": "",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 150,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 50,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "> 100 GB for OS > 50 GB for /mnt/resource - Deploy in PRIVATE VLAN"
      },
      {
        "Group": "C360",
        "Application": "C360 - Predix Service Host Server",
        "OS": "CentOS6.5 - 64bits",
        "Database": "",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 150,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 10,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "> 100 GB for OS > 50 GB for /mnt/resource - Deploy in PRIVATE VLAN"
      },
      {
        "Group": "C360",
        "Application": "C360 - EA Server & DB",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 700,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "> 40 GB for OS > 100 GB for SQL Database Server (D:) > 50GB for logs (E:), > 500GB encrypted (CIFS) - Deploy in PRIVATE VLAN"
      },
      {
        "Group": "C360",
        "Application": "C360 - Rabbit MQ & App File Syst.",
        "OS": "CentOS6.5 - 64bits",
        "Database": "",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 540,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 10,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "> 40 GB for OS >  500GB for  /data - To be deployed in PRIVATE VLAN"
      },
      {
        "Group": "C360",
        "Application": "C360 - ZFP and Dakota Server",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 50,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 10,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "> 50 GB for OS - Deploy in PRIVATE VLAN"
      },
      {
        "Group": "C360",
        "Application": "C360 - Active Directory",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 50,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 10,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "> 40 GB for OS > 10 GB for logs - Deploy in Management VLAN"
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia - Rhapsody (150 - 200 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 6,
        "vCPU": 2,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia - Rhapsody (up to 100 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia App Server + DB (100 - 150 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 24,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 4450,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia App Server + DB (150 - 200 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 24,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 4450,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia App Server + DB (20 - 60 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 16,
        "vCPU": 4,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 2900,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia App Server + DB (60 - 100 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 24,
        "vCPU": 6,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 3850,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia App Server + DB (up to 20 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 12,
        "vCPU": 4,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 2600,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia App Server + DB with PREDIX (100 - 150 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 32,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 4450,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia App Server + DB with PREDIX (150 - 200 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 32,
        "vCPU": 8,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 4450,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia App Server + DB with PREDIX (20 - 60 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 24,
        "vCPU": 4,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 2900,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia App Server + DB with PREDIX (60 - 100 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 32,
        "vCPU": 6,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 3850,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia App Server + DB with PREDIX (up to 20 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 12,
        "vCPU": 4,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 2600,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia Warehouse DB Server (100 - 150 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 8,
        "vCPU": 4,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia Warehouse DB Server (150 - 200 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 16,
        "vCPU": 4,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 2200,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia Warehouse DB Server (60 - 100 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 6,
        "vCPU": 4,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 1770,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "CA",
        "Application": "CA - Centricity Anaesthesia Warehouse DB Server (up to 20 clients)",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2012 Std",
        "vRAM": 4,
        "vCPU": 4,
        "RAID5GP1": 0,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 1770,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": ""
      },
      {
        "Group": "RIS_IC",
        "Application": "RIS_IC - RISDB",
        "OS": "W2K8 R2 SP1",
        "Database": "SQL 2012 Enterprise SP1",
        "vRAM": 16,
        "vCPU": 8,
        "RAID5GP1": 500,
        "RAID10GP2": 200,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "C:100GB/D:200GB/ E:100GB/H:300GB -Add room for paging file for C: and H: - memory = 10% of DB size"
      },
      {
        "Group": "RIS_IC",
        "Application": "RIS_IC - RISCXR",
        "OS": "W2K8 R2 SP1",
        "Database": "SQL 2012 Standard SP1",
        "vRAM": 16,
        "vCPU": 4,
        "RAID5GP1": 325,
        "RAID10GP2": 100,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "C:75GB/D:100GB/ E:100GB/H:150GB -Add room for paging file for C: and H:"
      },
      {
        "Group": "RIS_IC",
        "Application": "RIS_IC - RISWEB1",
        "OS": "W2K8 R2 SP1",
        "Database": "SQL 2012 Client Tool Connectivity",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 100,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "C:75GB"
      },
      {
        "Group": "RIS_IC",
        "Application": "RIS_IC - RISWEB2",
        "OS": "W2K8 R2 SP1",
        "Database": "SQL 2012 Client Tool Connectivity",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 100,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "C:75GB"
      },
      {
        "Group": "RIS_IC",
        "Application": "RIS_IC - RISRPT",
        "OS": "W2K8 R2 SP1",
        "Database": "SQL 2012 Client Tool Connectivity",
        "vRAM": 8,
        "vCPU": 4,
        "RAID5GP1": 175,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "C:75GB/D:100 - SAP Crystal Reports 2011, Microsoft Word 2010 (x86), Install PDF Reader"
      },
      {
        "Group": "RIS_IC",
        "Application": "RIS_IC - RISFAX",
        "OS": "W2K8 R2 SP1",
        "Database": "-",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 100,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "C:75GB - If VM - FOIP"
      },
      {
        "Group": "RIS_IC",
        "Application": "RIS_IC - RISTEST",
        "OS": "W2K8 R2 SP1",
        "Database": "SQL 2012 Standard SP1",
        "vRAM": 16,
        "vCPU": 4,
        "RAID5GP1": 500,
        "RAID10GP2": 200,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "C:100GB/D:200GB/ E:100GB/H:300GB -Add room for paging file for C: and H: - SAP Crystal Reports 2011 , Microsoft Word 2010 (x86), Install PDF Reader"
      },
      {
        "Group": "RIS_IC",
        "Application": "RIS_IC - RISPREDIX",
        "OS": "W2K8 R2 SP1",
        "Database": "SQL 2012 Client Tool Connectivity",
        "vRAM": 8,
        "vCPU": 4,
        "RAID5GP1": 100,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "C:100GB"
      },
      {
        "Group": "RIS_IC",
        "Application": "RIS_IC - RISALTRPT (If customer has Alt Rpt)",
        "OS": "W2K8 R2 SP1",
        "Database": "SQL 2012 Standard SP1",
        "vRAM": 16,
        "vCPU": "",
        "RAID5GP1": 500,
        "RAID10GP2": 200,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "C:100GB/D:200GB/ E:100GB/H:300GB -Add room for paging file for C: and H: - memory = 10% of DB size"
      },
      {
        "Group": "RIS_IC",
        "Application": "RIS_IC - RISDMS (If customer has DMS)",
        "OS": "W2K8 R2 SP1",
        "Database": "",
        "vRAM": 4,
        "vCPU": 2,
        "RAID5GP1": 325,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": "",
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "C:75GB/D:250GB - Generic disk sizes - actual disk sizes may vary based on customer need"
      },
      {
        "Group": "Other",
        "Application": "PACSHealth",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 8,
        "vCPU": 2,
        "RAID5GP1": 1120,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "C:\\OS - 60GB (Min.) \\ D:\\DATA - 900GB (Min.) - (Virtual servers can initially be less but MUST have expansion capability) \\ L:\\LOGS - 60GB (Min.)  \\ T:\\TEMP - 100GB (Min.)"
      },
      {
        "Group": "Other",
        "Application": "PACSGear DMWL",
        "OS": "MS 2012 R2 Std",
        "Database": "MS SQL 2014 Std",
        "vRAM": 4,
        "vCPU": 4,
        "RAID5GP1": 80,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Currently they do not have a VM specification document"
      },
      {
        "Group": "Other",
        "Application": "RMS Server",
        "OS": "Ubuntu 3.13.0",
        "Database": "MySQL 5.5.38",
        "vRAM": 2,
        "vCPU": 2,
        "RAID5GP1": 65,
        "RAID10GP2": 0,
        "RAID5GP3": 0,
        "RAID5GP4": 0,
        "IOPS": 100,
        "Interface1": "Fiber Channel",
        "Interface2": "SAS",
        "Interface3": "GigE",
        "Notes": "Delivered as an 3GB OVA"
      }
    ];

    return data;
  }
    

}
